export const cartConstants = {
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_RESET: 'CART_RESET',
  CART_ADD_DELIVERY_ADDRESS: 'CART_ADD_DELIVERY_ADDRESS',
  CART_SAVE_PAYMENT_METHOD: 'CART_SAVE_PAYMENT_METHOD',
}
