export const pizzaConstants = {
  PIZZA_LIST_REQUEST: 'PIZZA_LIST_REQUEST',
  PIZZA_LIST_SUCCESS: 'PIZZA_LIST_SUCCESS',
  PIZZA_LIST_FAIL: 'PIZZA_LIST_FAIL',
  PIZZA_DETAILS_REQUEST: 'PIZZA_DETAILS_REQUEST',
  PIZZA_DETAILS_SUCCESS: 'PIZZA_DETAILS_SUCCESS',
  PIZZA_DETAILS_FAIL: 'PIZZA_DETAILS_FAIL',
  PIZZA_TOPPINGS_REQUEST: 'PIZZA_TOPPINGS_REQUEST',
  PIZZA_TOPPINGS_SUCCESS: 'PIZZA_TOPPINGS_SUCCESS',
  PIZZA_TOPPINGS_FAIL: 'PIZZA_TOPPINGS_FAIL',
}
